# Generated by Django 3.1.1 on 2020-12-14 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('abrev', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='category',
            name='create_date',
            field=models.DateTimeField(verbose_name='Date creatio'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('unit_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(verbose_name='Date creatio')),
                ('update_date', models.DateTimeField(verbose_name='Date update')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.category')),
                ('id_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.vendor')),
            ],
        ),
    ]
